import type { Lang, Strings } from './types';

// Dil çevirileri — her ekrandaki sabit metinler burada, dil değişince otomatik güncellenir.
// Yeni bir dil eklemek istersen: buraya yeni bir bölüm (örn. `de: {...}`) ekle,
// sonra data.ts içindeki LANGS dizisine o dilin kodunu ekle.
export const STRINGS: Record<Lang, Strings> = {
  tr: {
    tapHint: 'Başlamak için ekrana dokunun',
    todaysMenuLabel: 'Bugünün Menüsü',
    announcementsLabel: 'Duyurular',
    idleWelcomeTitle: 'Karabük Üniversitesine Hoşgeldiniz',
    greetTitle: 'Merhaba!',
    greetSub: 'Size nasıl yardımcı olabilirim?',
    continueBtn: 'Devam et →',
    back: '← Geri',
    menuFind: 'Fakülte Hakkında',
    menuFindSub: 'Personel, sınav programı',
    menuAsk: 'Soru sor',
    menuAskSub: 'Sesli/metin asistan',
    menuMap: 'Kampüs haritası',
    menuMapSub: 'Kat planı göster',
    menuAbout: 'KBÜ Hakkında',
    menuAboutSub: 'Video, galeri, fakülteler',
    searchPlaceholder: 'Hoca adı yazın...',
    askPlaceholder: 'Sorunuzu yazın...',
    askSend: 'Gönder',
    askSending: 'Gönderiliyor...',
    askError: 'Bir hata oluştu, lütfen tekrar deneyin.',
    askReplay: 'Tekrar dinle',
    askListening: 'Dinleniyor...',
    askNotSupported: 'Tarayıcınız sesli girişi desteklemiyor.',
    noResult: 'Sonuç bulunamadı',
    getDirections: 'Yol tarifi al →',
    mapTitle: 'Neredeyim?',
    mapHint: "Kırmızı nokta robotun şu anki konumu (demo — gerçek konum Nav2'den gelecek)",
    videoCaption: 'Tanıtım Videosu',
    galleryCaption: 'Fotoğraf Galerisi',
    close: 'Kapat',
    tabFaculties: 'Fakülteler',
    degreeLisans: 'Lisans',
    degreeOnlisans: 'Ön Lisans',
    tabStaff: 'Personel',
    tabExam: 'Sınav Programı',
    staffSectionTitle: 'İdari Personel',
    contactLabel: 'İletişim',
    examCourse: 'Ders',
    examDemoNote: 'Örnek veri — sınav dönemi başlayınca güncel program burada gösterilecek.',
    examDate: 'Tarih',
    examTime: 'Saat',
    examRoom: 'Salon',
    menuGeneral: 'Genel Bilgiler',
    menuGeneralSub: 'Yemek listesi, akademik takvim',
    tabMenu: 'Yemek Listesi',
    tabCalendar: 'Akademik Takvim',
    menuOpenNewTab: 'Yeni Sekmede Aç ↗',
    operatorPinPrompt: 'Operatör PIN kodu',
    operatorLogin: 'Giriş',
    operatorWrongPin: 'Hatalı PIN',
    operatorTitle: 'Operatör Paneli',
    operatorSystemStatus: 'Sistem Durumu',
    operatorBattery: 'Pil',
    operatorActiveScreen: 'Aktif Ekran',
    operatorLang: 'Dil',
    operatorRestart: 'Sistemi Yeniden Başlat',
    operatorClearCache: 'Önbelleği Temizle',
    operatorExit: 'Kiosk Moduna Dön',
  },
  en: {
    tapHint: 'Touch screen to begin',
    todaysMenuLabel: "Today's Menu",
    announcementsLabel: 'Announcements',
    idleWelcomeTitle: 'Welcome to Karabük University',
    greetTitle: 'Hello!',
    greetSub: 'How can I help you?',
    continueBtn: 'Continue →',
    back: '← Back',
    menuFind: 'About Faculty',
    menuFindSub: 'Staff, exam schedule',
    menuAsk: 'Ask a question',
    menuAskSub: 'Voice/text assistant',
    menuMap: 'Campus map',
    menuMapSub: 'Show floor plan',
    menuAbout: 'About KBU',
    menuAboutSub: 'Video, gallery, faculties',
    searchPlaceholder: 'Type a name...',
    askPlaceholder: 'Type your question...',
    askSend: 'Send',
    askSending: 'Sending...',
    askError: 'Something went wrong, please try again.',
    askReplay: 'Replay',
    askListening: 'Listening...',
    askNotSupported: 'Your browser does not support voice input.',
    noResult: 'No results found',
    getDirections: 'Get directions →',
    mapTitle: 'Where Am I?',
    mapHint: "Red dot shows the robot's current position (demo — real position will come from Nav2)",
    videoCaption: 'Introduction Video',
    galleryCaption: 'Photo Gallery',
    close: 'Close',
    tabFaculties: 'Faculties',
    degreeLisans: "Bachelor's",
    degreeOnlisans: 'Associate',
    tabStaff: 'Staff',
    tabExam: 'Exam Schedule',
    staffSectionTitle: 'Administrative Staff',
    contactLabel: 'Contact',
    examCourse: 'Course',
    examDemoNote: 'Sample data — the current schedule will appear here once exam season begins.',
    examDate: 'Date',
    examTime: 'Time',
    examRoom: 'Room',
    menuGeneral: 'General Info',
    menuGeneralSub: 'Meal menu, academic calendar',
    tabMenu: 'Meal Menu',
    tabCalendar: 'Academic Calendar',
    menuOpenNewTab: 'Open in New Tab ↗',
    operatorPinPrompt: 'Operator PIN code',
    operatorLogin: 'Log in',
    operatorWrongPin: 'Incorrect PIN',
    operatorTitle: 'Operator Panel',
    operatorSystemStatus: 'System Status',
    operatorBattery: 'Battery',
    operatorActiveScreen: 'Active Screen',
    operatorLang: 'Language',
    operatorRestart: 'Restart System',
    operatorClearCache: 'Clear Cache',
    operatorExit: 'Return to Kiosk Mode',
  },
  ar: {
    tapHint: 'المس الشاشة للبدء',
    todaysMenuLabel: 'قائمة اليوم',
    announcementsLabel: 'الإعلانات',
    idleWelcomeTitle: 'مرحباً بكم في جامعة كارابوك',
    greetTitle: 'مرحباً!',
    greetSub: 'كيف يمكنني مساعدتك؟',
    continueBtn: 'متابعة ←',
    back: '→ رجوع',
    menuFind: 'عن الكلية',
    menuFindSub: 'الموظفون، جدول الامتحانات',
    menuAsk: 'اطرح سؤالاً',
    menuAskSub: 'مساعد صوتي/نصي',
    menuMap: 'خريطة الحرم الجامعي',
    menuMapSub: 'عرض المخطط',
    menuAbout: 'عن الجامعة',
    menuAboutSub: 'فيديو، معرض، كليات',
    searchPlaceholder: 'اكتب اسم الأستاذ...',
    askPlaceholder: 'اكتب سؤالك...',
    askSend: 'إرسال',
    askSending: 'جارٍ الإرسال...',
    askError: 'حدث خطأ، يرجى المحاولة مرة أخرى.',
    askReplay: 'إعادة الاستماع',
    askListening: 'جارٍ الاستماع...',
    askNotSupported: 'متصفحك لا يدعم الإدخال الصوتي.',
    noResult: 'لا توجد نتائج',
    getDirections: 'احصل على الاتجاهات ←',
    mapTitle: 'أين أنا؟',
    mapHint: 'النقطة الحمراء تُظهر موقع الروبوت الحالي (عرض تجريبي — الموقع الفعلي سيأتي من Nav2)',
    videoCaption: 'الفيديو التعريفي',
    galleryCaption: 'معرض الصور',
    close: 'إغلاق',
    tabFaculties: 'الكليات',
    degreeLisans: 'البكالوريوس',
    degreeOnlisans: 'الدبلوم',
    tabStaff: 'الموظفون',
    tabExam: 'جدول الامتحانات',
    staffSectionTitle: 'الموظفون الإداريون',
    contactLabel: 'التواصل',
    examCourse: 'المقرر',
    examDemoNote: 'بيانات تجريبية — سيظهر الجدول الفعلي هنا عند بدء فترة الامتحانات.',
    examDate: 'التاريخ',
    examTime: 'الوقت',
    examRoom: 'القاعة',
    menuGeneral: 'معلومات عامة',
    menuGeneralSub: 'قائمة الطعام، التقويم الأكاديمي',
    tabMenu: 'قائمة الطعام',
    tabCalendar: 'التقويم الأكاديمي',
    menuOpenNewTab: 'فتح في علامة تبويب جديدة ↗',
    operatorPinPrompt: 'رمز دخول المشغل',
    operatorLogin: 'دخول',
    operatorWrongPin: 'رمز غير صحيح',
    operatorTitle: 'لوحة المشغل',
    operatorSystemStatus: 'حالة النظام',
    operatorBattery: 'البطارية',
    operatorActiveScreen: 'الشاشة النشطة',
    operatorLang: 'اللغة',
    operatorRestart: 'إعادة تشغيل النظام',
    operatorClearCache: 'مسح ذاكرة التخزين المؤقت',
    operatorExit: 'العودة إلى وضع الكشك',
  },
};
