import type { CSSProperties } from 'react';

// Tüm ekranların paylaştığı stil tanımları — renk, font, boşluk gibi görsel ayarlar burada.
// Bir rengi/boyutu değiştirmek istersen sadece bu dosyaya bakman yeterli.
export const styles: Record<string, CSSProperties> = {
  root: {
    fontFamily: "'Inter', 'Cairo', sans-serif",
    background: '#F2F1ED',
    backgroundImage: 'radial-gradient(rgba(0,0,0,0.05) 1px, transparent 1px)',
    backgroundSize: '18px 18px',
    color: '#20211E',
    width: '100%',
    maxWidth: 1024,
    aspectRatio: '1024 / 600',
    margin: '0 auto',
    borderRadius: 16,
    padding: '20px 30px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
    minHeight: 0,
  },
  topBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  logo: {
    height: 28,
    width: 'auto',
  },
  eyebrow: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 13,
    letterSpacing: 1.5,
    color: '#6B7280',
  },
  clock: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 20,
    color: '#C8102E',
  },
  statusGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
  },
  batteryWrap: {
    display: 'flex',
    alignItems: 'center',
  },
  batteryBody: {
    position: 'relative',
    width: 26,
    height: 13,
    border: '1.5px solid #6B6E67',
    borderRadius: 3,
    overflow: 'hidden',
    padding: 1,
    boxSizing: 'border-box',
  },
  batteryFill: {
    height: '100%',
    background: '#2C6B27',
    borderRadius: 1,
  },
  batteryTip: {
    width: 2,
    height: 6,
    background: '#6B6E67',
    marginLeft: 1,
    borderRadius: 1,
  },
  langWrap: {
    position: 'relative',
  },
  langToggle: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 12,
    fontWeight: 500,
    color: '#20211E',
    background: '#E7E5DE',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 6,
    padding: '5px 10px',
    minHeight: 30,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  langDropdown: {
    position: 'absolute',
    top: '110%',
    right: 0,
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 8,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 72,
    boxShadow: '0 4px 12px rgba(0,0,0,0.12)',
    zIndex: 5,
  },
  langOption: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 12,
    fontWeight: 500,
    color: '#20211E',
    background: '#FFFFFF',
    border: 'none',
    padding: '10px 12px',
    minHeight: 40,
    textAlign: 'left',
    cursor: 'pointer',
  },
  langOptionActive: {
    color: '#F4EDEE',
    background: '#C8102E',
  },
  stage: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 18,
    paddingTop: 12,
    transition: 'all .6s ease',
    minHeight: 0,
  },
  idleWrap: {
    textAlign: 'center',
    maxWidth: 820,
    animation: 'fadeUp .5s ease',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    zIndex: 0,
  },
  idleWatermark: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 340,
    opacity: 0.05,
    pointerEvents: 'none',
    zIndex: -1,
  },
  idleGreetTitle: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 700,
    fontSize: 26,
    margin: '0 0 28px',
    color: '#20211E',
  },
  idleColumns: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 48,
    width: '100%',
  },
  idleClockCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flexShrink: 0,
    minWidth: 220,
  },
  idleInfoCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
    flex: 1,
    maxWidth: 420,
    textAlign: 'left',
    borderLeft: '1px solid rgba(0,0,0,0.08)',
    paddingLeft: 40,
  },
  idleClock: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontWeight: 500,
    fontSize: 58,
    color: '#20211E',
    lineHeight: 1,
  },
  idleDate: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 14,
    color: '#6B6E67',
    margin: '6px 0 0',
    textTransform: 'capitalize',
  },
  weatherLine: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontSize: 16,
    color: '#20211E',
    margin: '8px 0 0',
  },
  todaysMenuCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 12,
    padding: '12px 18px',
    width: '100%',
    boxSizing: 'border-box',
  },
  todaysMenuCardLabel: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 11,
    letterSpacing: 1,
    color: '#C8102E',
    textTransform: 'uppercase',
  },
  todaysMenuCardItems: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontSize: 15,
    color: '#20211E',
  },
  announcementCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    background: '#FFFFFF',
    borderLeft: '3px solid #C8102E',
    borderRadius: 8,
    padding: '10px 18px',
    width: '100%',
    boxSizing: 'border-box',
  },
  announcementCardLabel: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 11,
    letterSpacing: 1,
    color: '#C8102E',
    textTransform: 'uppercase',
  },
  dotRow: {
    display: 'flex',
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: 'rgba(0,0,0,0.15)',
  },
  dotActive: {
    background: '#C8102E',
  },
  announcement: {
    fontSize: 14,
    color: '#6B6E67',
    margin: 0,
  },
  tapHint: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 12,
    letterSpacing: 1,
    color: '#C8102E',
    margin: '26px 0 0',
    animation: 'fadeUp 1.8s ease-in-out infinite alternate',
  },
  greetTextWrap: { textAlign: 'left', paddingLeft: 8, animation: 'fadeUp .5s ease' },
  greetTitle: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 700,
    fontSize: 34,
    margin: '0 0 6px',
    color: '#20211E',
  },
  greetSub: {
    fontSize: 16,
    color: '#6B6E67',
    margin: '0 0 18px',
  },
  askWrap: {
    textAlign: 'left',
    paddingLeft: 8,
    width: '100%',
    maxWidth: 620,
    animation: 'fadeUp .5s ease',
  },
  askInputRow: {
    display: 'flex',
    gap: 10,
  },
  micBtn: {
    fontSize: 18,
    width: 44,
    height: 44,
    flexShrink: 0,
    borderRadius: '50%',
    border: '1px solid rgba(0,0,0,0.12)',
    background: '#E7E5DE',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  micBtnActive: {
    background: '#C8102E',
    animation: 'pulseMic 1.4s ease-out infinite',
  },
  askAnswerCard: {
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 12,
    padding: '16px 20px',
    marginTop: 16,
  },
  askAnswerText: {
    fontSize: 15,
    color: '#20211E',
    lineHeight: 1.5,
    margin: 0,
  },
  askReplayBtn: {
    fontFamily: "'Inter', 'Cairo', sans-serif",
    fontSize: 12,
    color: '#6B6E67',
    background: 'transparent',
    border: 'none',
    padding: '10px 0 0',
    cursor: 'pointer',
  },
  cta: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 500,
    fontSize: 16,
    color: '#F4EDEE',
    background: '#C8102E',
    border: 'none',
    borderRadius: 10,
    padding: '14px 28px',
    minHeight: 48,
    cursor: 'pointer',
  },
  menuWrap: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 14,
    width: '100%',
    maxWidth: 620,
    animation: 'fadeUp .5s ease',
  },
  menuCard: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 12,
    padding: '18px 16px',
    minHeight: 90,
    cursor: 'pointer',
    textAlign: 'left',
  },
  menuCardTitle: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 500,
    fontSize: 16,
    color: '#20211E',
  },
  menuCardSub: {
    fontSize: 13,
    color: '#6B6E67',
  },
  backLink: {
    alignSelf: 'flex-start',
    fontFamily: "'Inter', 'Cairo', sans-serif",
    fontSize: 13,
    color: '#6B6E67',
    background: 'transparent',
    border: 'none',
    padding: '4px 0',
    cursor: 'pointer',
  },
  findWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    width: '100%',
    maxWidth: 860,
    flex: 1,
    minHeight: 0,
    boxSizing: 'border-box',
    animation: 'fadeUp .5s ease',
  },
  facultyListSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    flex: 1,
    minHeight: 0,
    width: '100%',
    boxSizing: 'border-box',
  },
  facultyListFill: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    width: '100%',
    boxSizing: 'border-box',
  },
  tabRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  tabBtn: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontSize: 13,
    fontWeight: 500,
    color: '#6B6E67',
    background: '#E7E5DE',
    border: 'none',
    borderRadius: 8,
    padding: '8px 14px',
    minHeight: 36,
    cursor: 'pointer',
  },
  tabBtnActive: {
    color: '#F4EDEE',
    background: '#C8102E',
  },
  facultyRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 2,
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.08)',
    borderRadius: 8,
    padding: '10px 14px',
    width: '100%',
    boxSizing: 'border-box',
  },
  examTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 13,
  },
  examTh: {
    textAlign: 'left',
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 500,
    color: '#6B6E67',
    padding: '6px 8px',
    borderBottom: '1px solid rgba(0,0,0,0.1)',
  },
  examTd: {
    padding: '8px 8px',
    borderBottom: '1px solid rgba(0,0,0,0.06)',
    color: '#20211E',
  },
  searchInput: {
    fontFamily: "'Inter', 'Cairo', sans-serif",
    fontSize: 15,
    color: '#20211E',
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.15)',
    borderRadius: 10,
    padding: '12px 14px',
    minHeight: 44,
    outline: 'none',
    boxSizing: 'border-box',
  },
  profList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    maxHeight: 150,
    overflowY: 'auto',
  },
  calendarList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  profRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 2,
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.08)',
    borderRadius: 8,
    padding: '10px 14px',
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
    boxSizing: 'border-box',
  },
  profName: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 500,
    fontSize: 14,
    color: '#20211E',
  },
  profDept: {
    fontSize: 12,
    color: '#6B6E67',
  },
  noResult: {
    fontSize: 13,
    color: '#6B6E67',
    margin: 0,
  },
  profDetail: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
    background: '#FFFFFF',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 12,
    padding: '18px 20px',
    marginTop: 4,
  },
  profDetailName: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 500,
    fontSize: 18,
    margin: 0,
    color: '#20211E',
  },
  profDetailInfo: {
    fontSize: 14,
    color: '#6B6E67',
    margin: 0,
  },
  profStatus: {
    fontFamily: "'IBM Plex Mono', 'Cairo', monospace",
    fontSize: 12,
    padding: '4px 10px',
    borderRadius: 20,
  },
  statusIn: {
    background: '#E4F0E3',
    color: '#2C6B27',
  },
  statusOut: {
    background: '#F3E3E3',
    color: '#8C2F2F',
  },
  mapWrap: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    maxWidth: 860,
    flex: 1,
    minHeight: 0,
    boxSizing: 'border-box',
    animation: 'fadeUp .5s ease',
  },
  mapTitle: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 700,
    fontSize: 20,
    color: '#20211E',
    margin: 0,
    alignSelf: 'flex-start',
  },
  mapSvg: {
    width: '100%',
    flex: 1,
    minHeight: 0,
  },
  mapLabel: {
    fontFamily: "'Inter', 'Cairo', sans-serif",
    fontSize: 11,
    fill: '#20211E',
  },
  mapRobotLabel: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontSize: 12,
    fontWeight: 700,
    fill: '#C8102E',
  },
  mapHint: {
    fontSize: 12,
    color: '#6B6E67',
    margin: 0,
  },
  linkOutBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    flex: 1,
    minHeight: 0,
  },
  pdfFrame: {
    width: '100%',
    flex: 1,
    minHeight: 0,
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 10,
    background: '#FFFFFF',
  },
  aboutWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    width: '100%',
    maxWidth: 860,
    flex: 1,
    minHeight: 0,
    boxSizing: 'border-box',
    animation: 'fadeUp .5s ease',
  },
  aboutSectionTitle: {
    fontFamily: "'Space Grotesk', 'Cairo', sans-serif",
    fontWeight: 500,
    fontSize: 13,
    color: '#6B6E67',
    margin: '6px 0 0',
  },
  aboutVideoFrame: {
    width: '100%',
    flex: 1,
    minHeight: 0,
    borderRadius: 10,
    overflow: 'hidden',
    background: '#20211E',
  },
  aboutVideoIframe: {
    width: '100%',
    height: '100%',
    border: 'none',
  },
  galleryRow: {
    display: 'flex',
    gap: 12,
    flex: 1,
    minHeight: 0,
  },
  galleryThumb: {
    position: 'relative',
    flex: 1,
    minWidth: 0,
    height: '100%',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 10,
    overflow: 'hidden',
    padding: 0,
    cursor: 'pointer',
    background: '#E7E5DE',
  },
  galleryThumbImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  galleryThumbFallback: {
    display: 'none',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
  },
  lightboxOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(0,0,0,0.55)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  lightboxBox: {
    background: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    width: '80%',
    maxWidth: 560,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
  },
  lightboxImg: {
    width: '100%',
    height: 280,
    borderRadius: 8,
    objectFit: 'contain',
    background: '#20211E',
  },
  lightboxCaption: {
    fontSize: 13,
    color: '#6B6E67',
    margin: 0,
  },
  lightboxNav: {
    display: 'flex',
    gap: 10,
  },
  lightboxBtn: {
    fontFamily: "'Inter', 'Cairo', sans-serif",
    fontSize: 13,
    color: '#20211E',
    background: '#E7E5DE',
    border: 'none',
    borderRadius: 8,
    padding: '8px 14px',
    minHeight: 36,
    cursor: 'pointer',
  },
  gearBtn: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: '50%',
    border: '1px solid rgba(0,0,0,0.08)',
    background: 'rgba(0,0,0,0.04)',
    color: '#6B6E67',
    fontSize: 13,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    opacity: 0.6,
  },
  operatorAuthBox: {
    background: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    minWidth: 220,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
  },
  operatorBox: {
    background: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxWidth: 340,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  pinErrorText: {
    fontSize: 12,
    color: '#8C2F2F',
    margin: 0,
  },
};
